# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mytime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mytime.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmytime.proto\"<\n\x0b\x45pochChange\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x0e\n\x06period\x18\x02 \x01(\r\x12\r\n\x05start\x18\x03 \x01(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EPOCHCHANGE = _descriptor.Descriptor(
  name='EpochChange',
  full_name='EpochChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='EpochChange.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='period', full_name='EpochChange.period', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='EpochChange.start', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['EpochChange'] = _EPOCHCHANGE

EpochChange = _reflection.GeneratedProtocolMessageType('EpochChange', (_message.Message,), dict(
  DESCRIPTOR = _EPOCHCHANGE,
  __module__ = 'mytime_pb2'
  # @@protoc_insertion_point(class_scope:EpochChange)
  ))
_sym_db.RegisterMessage(EpochChange)


# @@protoc_insertion_point(module_scope)
