// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dune.proto

#ifndef PROTOBUF_dune_2eproto__INCLUDED
#define PROTOBUF_dune_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dune_2eproto();
void protobuf_AssignDesc_dune_2eproto();
void protobuf_ShutdownFile_dune_2eproto();

class ChannelActivity;
class PrimitiveActivity;

// ===================================================================

class ChannelActivity : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ChannelActivity) */ {
 public:
  ChannelActivity();
  virtual ~ChannelActivity();

  ChannelActivity(const ChannelActivity& from);

  inline ChannelActivity& operator=(const ChannelActivity& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelActivity& default_instance();

  void Swap(ChannelActivity* other);

  // implements Message ----------------------------------------------

  inline ChannelActivity* New() const { return New(NULL); }

  ChannelActivity* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChannelActivity& from);
  void MergeFrom(const ChannelActivity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChannelActivity* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 channel = 1;
  void clear_channel();
  static const int kChannelFieldNumber = 1;
  ::google::protobuf::uint32 channel() const;
  void set_channel(::google::protobuf::uint32 value);

  // optional uint32 start_tick = 3;
  void clear_start_tick();
  static const int kStartTickFieldNumber = 3;
  ::google::protobuf::uint32 start_tick() const;
  void set_start_tick(::google::protobuf::uint32 value);

  // optional uint32 duration = 4;
  void clear_duration();
  static const int kDurationFieldNumber = 4;
  ::google::protobuf::uint32 duration() const;
  void set_duration(::google::protobuf::uint32 value);

  // optional uint32 activity = 5;
  void clear_activity();
  static const int kActivityFieldNumber = 5;
  ::google::protobuf::uint32 activity() const;
  void set_activity(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ChannelActivity)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 channel_;
  ::google::protobuf::uint32 start_tick_;
  ::google::protobuf::uint32 duration_;
  ::google::protobuf::uint32 activity_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_dune_2eproto();
  friend void protobuf_AssignDesc_dune_2eproto();
  friend void protobuf_ShutdownFile_dune_2eproto();

  void InitAsDefaultInstance();
  static ChannelActivity* default_instance_;
};
// -------------------------------------------------------------------

class PrimitiveActivity : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PrimitiveActivity) */ {
 public:
  PrimitiveActivity();
  virtual ~PrimitiveActivity();

  PrimitiveActivity(const PrimitiveActivity& from);

  inline PrimitiveActivity& operator=(const PrimitiveActivity& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PrimitiveActivity& default_instance();

  void Swap(PrimitiveActivity* other);

  // implements Message ----------------------------------------------

  inline PrimitiveActivity* New() const { return New(NULL); }

  PrimitiveActivity* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrimitiveActivity& from);
  void MergeFrom(const PrimitiveActivity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrimitiveActivity* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 fragid = 1;
  void clear_fragid();
  static const int kFragidFieldNumber = 1;
  ::google::protobuf::uint32 fragid() const;
  void set_fragid(::google::protobuf::uint32 value);

  // optional uint32 count = 2;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::uint32 count() const;
  void set_count(::google::protobuf::uint32 value);

  // optional int64 reference_tick = 3;
  void clear_reference_tick();
  static const int kReferenceTickFieldNumber = 3;
  ::google::protobuf::int64 reference_tick() const;
  void set_reference_tick(::google::protobuf::int64 value);

  // repeated .ChannelActivity primitives = 5;
  int primitives_size() const;
  void clear_primitives();
  static const int kPrimitivesFieldNumber = 5;
  const ::ChannelActivity& primitives(int index) const;
  ::ChannelActivity* mutable_primitives(int index);
  ::ChannelActivity* add_primitives();
  ::google::protobuf::RepeatedPtrField< ::ChannelActivity >*
      mutable_primitives();
  const ::google::protobuf::RepeatedPtrField< ::ChannelActivity >&
      primitives() const;

  // @@protoc_insertion_point(class_scope:PrimitiveActivity)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 fragid_;
  ::google::protobuf::uint32 count_;
  ::google::protobuf::int64 reference_tick_;
  ::google::protobuf::RepeatedPtrField< ::ChannelActivity > primitives_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_dune_2eproto();
  friend void protobuf_AssignDesc_dune_2eproto();
  friend void protobuf_ShutdownFile_dune_2eproto();

  void InitAsDefaultInstance();
  static PrimitiveActivity* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ChannelActivity

// optional uint32 channel = 1;
inline void ChannelActivity::clear_channel() {
  channel_ = 0u;
}
inline ::google::protobuf::uint32 ChannelActivity::channel() const {
  // @@protoc_insertion_point(field_get:ChannelActivity.channel)
  return channel_;
}
inline void ChannelActivity::set_channel(::google::protobuf::uint32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:ChannelActivity.channel)
}

// optional uint32 start_tick = 3;
inline void ChannelActivity::clear_start_tick() {
  start_tick_ = 0u;
}
inline ::google::protobuf::uint32 ChannelActivity::start_tick() const {
  // @@protoc_insertion_point(field_get:ChannelActivity.start_tick)
  return start_tick_;
}
inline void ChannelActivity::set_start_tick(::google::protobuf::uint32 value) {
  
  start_tick_ = value;
  // @@protoc_insertion_point(field_set:ChannelActivity.start_tick)
}

// optional uint32 duration = 4;
inline void ChannelActivity::clear_duration() {
  duration_ = 0u;
}
inline ::google::protobuf::uint32 ChannelActivity::duration() const {
  // @@protoc_insertion_point(field_get:ChannelActivity.duration)
  return duration_;
}
inline void ChannelActivity::set_duration(::google::protobuf::uint32 value) {
  
  duration_ = value;
  // @@protoc_insertion_point(field_set:ChannelActivity.duration)
}

// optional uint32 activity = 5;
inline void ChannelActivity::clear_activity() {
  activity_ = 0u;
}
inline ::google::protobuf::uint32 ChannelActivity::activity() const {
  // @@protoc_insertion_point(field_get:ChannelActivity.activity)
  return activity_;
}
inline void ChannelActivity::set_activity(::google::protobuf::uint32 value) {
  
  activity_ = value;
  // @@protoc_insertion_point(field_set:ChannelActivity.activity)
}

// -------------------------------------------------------------------

// PrimitiveActivity

// optional uint32 fragid = 1;
inline void PrimitiveActivity::clear_fragid() {
  fragid_ = 0u;
}
inline ::google::protobuf::uint32 PrimitiveActivity::fragid() const {
  // @@protoc_insertion_point(field_get:PrimitiveActivity.fragid)
  return fragid_;
}
inline void PrimitiveActivity::set_fragid(::google::protobuf::uint32 value) {
  
  fragid_ = value;
  // @@protoc_insertion_point(field_set:PrimitiveActivity.fragid)
}

// optional uint32 count = 2;
inline void PrimitiveActivity::clear_count() {
  count_ = 0u;
}
inline ::google::protobuf::uint32 PrimitiveActivity::count() const {
  // @@protoc_insertion_point(field_get:PrimitiveActivity.count)
  return count_;
}
inline void PrimitiveActivity::set_count(::google::protobuf::uint32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:PrimitiveActivity.count)
}

// optional int64 reference_tick = 3;
inline void PrimitiveActivity::clear_reference_tick() {
  reference_tick_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PrimitiveActivity::reference_tick() const {
  // @@protoc_insertion_point(field_get:PrimitiveActivity.reference_tick)
  return reference_tick_;
}
inline void PrimitiveActivity::set_reference_tick(::google::protobuf::int64 value) {
  
  reference_tick_ = value;
  // @@protoc_insertion_point(field_set:PrimitiveActivity.reference_tick)
}

// repeated .ChannelActivity primitives = 5;
inline int PrimitiveActivity::primitives_size() const {
  return primitives_.size();
}
inline void PrimitiveActivity::clear_primitives() {
  primitives_.Clear();
}
inline const ::ChannelActivity& PrimitiveActivity::primitives(int index) const {
  // @@protoc_insertion_point(field_get:PrimitiveActivity.primitives)
  return primitives_.Get(index);
}
inline ::ChannelActivity* PrimitiveActivity::mutable_primitives(int index) {
  // @@protoc_insertion_point(field_mutable:PrimitiveActivity.primitives)
  return primitives_.Mutable(index);
}
inline ::ChannelActivity* PrimitiveActivity::add_primitives() {
  // @@protoc_insertion_point(field_add:PrimitiveActivity.primitives)
  return primitives_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ChannelActivity >*
PrimitiveActivity::mutable_primitives() {
  // @@protoc_insertion_point(field_mutable_list:PrimitiveActivity.primitives)
  return &primitives_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ChannelActivity >&
PrimitiveActivity::primitives() const {
  // @@protoc_insertion_point(field_list:PrimitiveActivity.primitives)
  return primitives_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dune_2eproto__INCLUDED
