#!/usr/bin/env waf
'''

$ PKG_CONFIG_PATH=$HOME/opt/zmq/lib/pkgconfig waf configure 

'''

def options(opt):
    opt.load('compiler_c compiler_cxx')

def configure(cfg):
    cfg.load('compiler_c compiler_cxx')
    cfg.check_cfg(package='libzyre', uselib_store='ZYRE',
                  args=['--cflags', '--libs'], mandatory=False)
    cfg.check_cfg(package='libczmq', uselib_store='CZMQ',
                  args=['--cflags', '--libs'], mandatory=True)
    cfg.env.CXXFLAGS=["-g"]

def build(bld):
    progs=["gossipper"]
    uses=["CZMQ"]
    if bld.env.HAVE_ZYRE:
        uses.append("ZYRE")
        progs += "ironhouse ironhouse2 curve-keygen".split()
    for prog in progs:
        t = bld(features='c cxx cxxprogram', use=uses,
                source=prog+'.cc', target=prog)
        t.rpath=bld.env['LIBPATH_ZYRE']
