# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dune.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dune.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ndune.proto\"Z\n\x0f\x43hannelActivity\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\r\x12\x12\n\nstart_tick\x18\x03 \x01(\r\x12\x10\n\x08\x64uration\x18\x04 \x01(\r\x12\x10\n\x08\x61\x63tivity\x18\x05 \x01(\r\"p\n\x11PrimitiveActivity\x12\x0e\n\x06\x66ragid\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x16\n\x0ereference_tick\x18\x03 \x01(\x03\x12$\n\nprimitives\x18\x05 \x03(\x0b\x32\x10.ChannelActivityb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHANNELACTIVITY = _descriptor.Descriptor(
  name='ChannelActivity',
  full_name='ChannelActivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='ChannelActivity.channel', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_tick', full_name='ChannelActivity.start_tick', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='ChannelActivity.duration', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity', full_name='ChannelActivity.activity', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=104,
)


_PRIMITIVEACTIVITY = _descriptor.Descriptor(
  name='PrimitiveActivity',
  full_name='PrimitiveActivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fragid', full_name='PrimitiveActivity.fragid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='PrimitiveActivity.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_tick', full_name='PrimitiveActivity.reference_tick', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='primitives', full_name='PrimitiveActivity.primitives', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=218,
)

_PRIMITIVEACTIVITY.fields_by_name['primitives'].message_type = _CHANNELACTIVITY
DESCRIPTOR.message_types_by_name['ChannelActivity'] = _CHANNELACTIVITY
DESCRIPTOR.message_types_by_name['PrimitiveActivity'] = _PRIMITIVEACTIVITY

ChannelActivity = _reflection.GeneratedProtocolMessageType('ChannelActivity', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELACTIVITY,
  __module__ = 'dune_pb2'
  # @@protoc_insertion_point(class_scope:ChannelActivity)
  ))
_sym_db.RegisterMessage(ChannelActivity)

PrimitiveActivity = _reflection.GeneratedProtocolMessageType('PrimitiveActivity', (_message.Message,), dict(
  DESCRIPTOR = _PRIMITIVEACTIVITY,
  __module__ = 'dune_pb2'
  # @@protoc_insertion_point(class_scope:PrimitiveActivity)
  ))
_sym_db.RegisterMessage(PrimitiveActivity)


# @@protoc_insertion_point(module_scope)
